#################################### common config : ####################################
spring:
  application:
    name: exchange-stream
  datasource:
    url: jdbc:mysql://adev.top:3306/adev-gather?serverTimezone=UTC
    username: root
    password: 239ea79e9e2a61df
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update #important! Don't change!
      use-new-id-generator-mappings: true
    show-sql: false
  rabbitmq:
    host: adev.top
    port: 5672
    virtual-host: adev_vhost
    username: admin
    password: adev.top
# 应用服务web访问端口
server:
  port: 8089

---
spring:
  profiles: test
# eureka客户端配置
eureka:
  instance:
    # 使用 ip 代替实例名
    prefer-ip-address: true
    # 实例的主机名
    hostname: ${spring.cloud.client.ip-address}
    # 实例的 ID 规则
    instance-id: ${spring.cloud.client.ip-address}:${spring.application.name}:${server.port}
  client:
    serviceUrl:
      # 注册中心地址
      defaultZone: http://adev.top:8761/eureka/,http://adev.top:8762/eureka/

#定于交易所信息
subscribe:
  exchanges[0]:
    name: kraken
    class-name: com.adev.exchange.stream.exchange.kraken.KrakenStreamingExchange
    all-ticker: false
  exchanges[1]:
      name: coinone
      class-name: com.adev.exchange.stream.exchange.coinone.CoinoneStreamingExchange
      all-ticker: true
  exchanges[2]:
        name: bitbank
        class-name: com.adev.exchange.stream.exchange.bitbank.BitbankStreamingExchange
        all-ticker: false
---
spring:
  profiles: dev
# eureka客户端配置
eureka:
  instance:
    # 使用 ip 代替实例名
    prefer-ip-address: true
    # 实例的主机名
    hostname: ${spring.cloud.client.ip-address}
    # 实例的 ID 规则
    instance-id: ${spring.cloud.client.ip-address}:${spring.application.name}:${server.port}
  client:
    serviceUrl:
      # 注册中心地址
      defaultZone: http://127.0.0.1:8761/eureka/

#定于交易所信息
subscribe:
  exchanges[0]:
    name: kraken
    class-name: com.adev.exchange.stream.exchange.kraken.KrakenStreamingExchange
    all-ticker: false
  exchanges[1]:
    name: coinone
    class-name: com.adev.exchange.stream.exchange.coinone.CoinoneStreamingExchange
    all-ticker: true
  exchanges[2]:
    name: bitbank
    class-name: com.adev.exchange.stream.exchange.bitbank.BitbankStreamingExchange
    all-ticker: false


      